(define tax_rate 0.065)
(define (start)
    (display "Scheme Point-of-Sale")
    (display "Start transaction (exit with 0):\n")
    (let ((num (read))) (getValue num 0))
)

(define (getValue input subtotal)
    (cond
        ((equal? input 0)
        (display "Subtotal: ")
        (display subtotal)
        (display "")
        (display "Tax: ")
        (display (* subtotal tax_rate))
        (display "")
        (display "Total: ")
        (display (+ subtotal (* subtotal tax_rate))) #t)
    (else (display "Enter amount: ")
        (let ((num ((read))) (getValue num (+ input subtotal))))
    )
    )
)

